### ISSUE TITLE
Legofy at PyPI

### ISSUE THREAD

**Issue by hugovk** [oliveirarodolfo/legofy#4]
Hello,

You have the PyPI package named "legofy" at: https://pypi.python.org/pypi/legofy

I notice there's no downloads on that page. 

Are you still interested in it? Or would you be happy to let someone else to use that name at PyPI?

Just to let you know there's another, recent Python library by @JuanPotato to make Lego versions of images:

https://github.com/JuanPotato/Legofy/

JuanPotato has requested the name here: http://sourceforge.net/p/pypi/support-requests/562/

I've not used either of these libraries, but just thought I should post here to help things along.

Cheers!

**Comment by oliveirarodolfo** [comment]
Hi,

I've seen the discussion over his ticket: https://github.com/JuanPotato/Legofy/issues/82

I've let my project register go in favor of his. This was never meant to be an ambitious project, it was simply a not so tedious way to study some modules. 

I'm really surprise that I got a *name* conflict for such a package. :smile:

**Comment by JuanPotato** [comment]
Thank you very much :D
